window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isIE=!!document.documentMode;window.browserLang=(window.navigator.userLanguage||window.navigator.language).toUpperCase().slice(0,2);window.tildaBrowserLang=window.browserLang;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t456_setListMagin(recid,imglogo){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menu=rec.querySelector('.t456');var leftSide=menu?menu.querySelector('.t456__leftwrapper'):null;var list=menu?menu.querySelector('.t456__list'):null;var leftSideWidth=leftSide?leftSide.offsetWidth:0;if(list)list.style.marginRight=(imglogo?leftSideWidth:leftSideWidth+30)+'px'}
function t280_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var isChrome=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor);var isAndroid=/(android)/i.test(navigator.userAgent);var menu=rec.querySelector('.t280');var menuItems=rec.querySelectorAll('.t280__menu__item');var menuLinks=rec.querySelectorAll('.t978__menu-link');var menuContainer=rec.querySelector('.t280__menu');var clickElementsList=rec.querySelectorAll('.t280__burger, .t280__menu__bg, .t280__menu__item:not(.tooltipstered):not(.t280__menu__item_submenu), .t978__tooltip-menu_mobile');Array.prototype.forEach.call(clickElementsList,function(clickElement){clickElement.addEventListener('click',function(){if(clickElement.closest('.t280__menu__item.tooltipstered')||clickElement.closest('.t794__tm-link'))return;if(isChrome&&isAndroid&&menuItems.length>10&&window.location.hash){setTimeout(function(){var hash=window.location.hash;window.location.hash='';window.location.hash=hash},50)}
if(!clickElement.closest('.t978__tm-link, .t966__tm-link')){document.body.classList.toggle('t280_opened');if(menu)menu.classList.toggle('t280__main_opened');var menuHead=rec.querySelector('.t280__container');if(menuContainer)menuContainer.style.paddingTop=(menuHead?menuHead.offsetHeight:0)+'px'}
t280_changeSize(recid);t280_highlight(recid)})});document.addEventListener('click',function(e){if(e.target.closest('.t978__tm-link, .t966__tm-link, .t-menusub__target-link')){t280_changeSize(recid);if(menuContainer)menuContainer.style.transition='none'}});Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t280_changeSize(recid)})});if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){document.body.classList.remove('t280_opened');menu.classList.remove('t280__main_opened')})}
var submenuLinks=rec.querySelectorAll('.t-menusub__link-item');Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){document.body.classList.remove('t280_opened');if(menu)menu.classList.remove('t280__main_opened')})})}
function t280_changeSize(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t280__menu');var menuBottom=rec.querySelector('.t280__bottom');var menuContainer=rec.querySelector('.t280__container');var menuWrapper=rec.querySelector('.t280__menu__wrapper');setTimeout(function(){var menuHeight=menu?menu.offsetHeight:0;var menuBottomHeight=menuBottom?menuBottom.offsetHeight:0;var menuContainerHeight=menuContainer?menuContainer.offsetHeight:0;var padding=140;if(menuHeight>document.documentElement.clientHeight-(menuBottomHeight+menuContainerHeight+padding)){if(menuWrapper)menuWrapper.classList.add('t280__menu_static')}else{if(menuWrapper)menuWrapper.classList.remove('t280__menu_static')}},100)}
function t280_changeBgOpacityMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlocks=rec.querySelectorAll('.t280__container__bg');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity2');var menuShadow=menu.getAttribute('data-menu-shadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t280_appearMenu(){var menuBlocks=document.querySelectorAll('.t280');Array.prototype.forEach.call(menuBlocks,function(menuBlock){var menu=menuBlock.querySelector('.t280__positionfixed');if(menu){var appearOffset=menuBlock.getAttribute('data-appearoffset');if(appearOffset&&appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(isNaN(appearOffset))return;if(window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t280_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t280_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t280_slideUpElement(menu,menuHeight,direction){var diff=direction==='toTop'?0:menuHeight;var diffOpacity=direction==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=direction==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=direction==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(direction==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(direction==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t280_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t280__menu a[href=\''+url+'\'], '+'.t280__menu a[href=\''+url+'/\'], '+'.t280__menu a[href=\''+pathname+'\'], '+'.t280__menu a[href=\'/'+pathname+'\'], '+'.t280__menu a[href=\''+pathname+'/\'], '+'.t280__menu a[href=\'/'+pathname+'/\']'+(hash?', .t280__menu a[href=\''+hash+'\']':'')+(hash?', .t280__menu a[href=\'/'+hash+'\']':'')+(hash?', .t280__menu a[href=\''+hash+'/\']':'')+(hash?', .t280__menu a[href=\'/'+hash+'/\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t280__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t985_init(recid,searchVariants){var rec=document.querySelector('#rec'+recid);if(!rec)return;if(searchVariants.length>0){t985_addSearchVariants(recid,searchVariants)}
var searchWidgetIcon=rec.querySelectorAll('.t985__search-widget-icon');Array.prototype.forEach.call(searchWidgetIcon,function(widgetIcon){widgetIcon.addEventListener('click',function(){t985_showSearch(rec)})});var closeIcon=rec.querySelector('.t985__close-icon');if(closeIcon){closeIcon.addEventListener('click',function(){t985_hideSearch(rec)})}
var overlay=rec.querySelector('.t985__overlay');if(overlay){overlay.addEventListener('click',function(event){var target=event.target;var parentTarget=target.parentElement;if(!target.classList.contains('.t985__widgetheader')&&!parentTarget.classList.contains('.t985__widgetheader')){t985_hideSearch(rec)}})}}
function t985_addSearchVariants(recid,searchVariants){var rec=document.querySelector('#rec'+recid);if(!rec)return;var container=rec.querySelector('.t985__searchvariants');var searchArray=searchVariants.split(',');Array.prototype.forEach.call(searchArray,function(variant){container.innerHTML+='<div class="t985__searchvariant t-text t-text_xs">'+variant+'</div>'})}
function t985_showSearch(rec){rec.querySelector('.t985__overlay').style.display='block';rec.querySelector('.t985__search-widget-icon').style.display='none'}
function t985_hideSearch(rec){rec.querySelector('.t985__overlay').style.display='none';rec.querySelector('.t985__search-widget-icon').style.display='block'}
function t890_init(recId,offset){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t890');if(!container)return;var button=rec.querySelector('.t890__arrow');var windowOffset='';if(offset){windowOffset=offset}else{windowOffset=window.innerHeight}
rec.setAttribute('data-animationappear','off');rec.style.opacity=1;window.addEventListener('scroll',t_throttle(function(){if(window.pageYOffset>windowOffset){container.style.display='block'}else{t890__fadeOut(container)}},200));button.addEventListener('click',function(){var isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);if(isSafari){t890__animateScrollPolyfill(0)}else{t890__scrollToTop()}})}
function t890__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},20)}
function t890__scrollToTop(){if(window.isIE){window.scrollTo(0,0)}else{window.scrollTo({left:0,top:0,behavior:'smooth'})}}
function t890__animateScrollPolyfill(target){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(target>bottomViewportPoint)target=bottomViewportPoint;if(target===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(target-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if((target-currentPosition<0&&window.pageYOffset<=target)||(target-currentPosition>0&&window.pageYOffset>=target)){clearInterval(timerID);document.body.removeAttribute('data-scrollable')}},10)}