window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isIE=!!document.documentMode;window.browserLang=(window.navigator.userLanguage||window.navigator.language).toUpperCase().slice(0,2);window.tildaBrowserLang=window.browserLang;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t456_setListMagin(recid,imglogo){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menu=rec.querySelector('.t456');var leftSide=menu?menu.querySelector('.t456__leftwrapper'):null;var list=menu?menu.querySelector('.t456__list'):null;var leftSideWidth=leftSide?leftSide.offsetWidth:0;if(list)list.style.marginRight=(imglogo?leftSideWidth:leftSideWidth+30)+'px'}
function t280_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var isChrome=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor);var isAndroid=/(android)/i.test(navigator.userAgent);var menu=rec.querySelector('.t280');var menuItems=rec.querySelectorAll('.t280__menu__item');var menuLinks=rec.querySelectorAll('.t978__menu-link');var menuContainer=rec.querySelector('.t280__menu');var clickElementsList=rec.querySelectorAll('.t280__burger, .t280__menu__bg, .t280__menu__item:not(.tooltipstered):not(.t280__menu__item_submenu), .t978__tooltip-menu_mobile');Array.prototype.forEach.call(clickElementsList,function(clickElement){clickElement.addEventListener('click',function(){if(clickElement.closest('.t280__menu__item.tooltipstered')||clickElement.closest('.t794__tm-link'))return;if(isChrome&&isAndroid&&menuItems.length>10&&window.location.hash){setTimeout(function(){var hash=window.location.hash;window.location.hash='';window.location.hash=hash},50)}
if(!clickElement.closest('.t978__tm-link, .t966__tm-link')){document.body.classList.toggle('t280_opened');if(menu)menu.classList.toggle('t280__main_opened');var menuHead=rec.querySelector('.t280__container');if(menuContainer)menuContainer.style.paddingTop=(menuHead?menuHead.offsetHeight:0)+'px'}
t280_changeSize(recid);t280_highlight(recid)})});document.addEventListener('click',function(e){if(e.target.closest('.t978__tm-link, .t966__tm-link, .t-menusub__target-link')){t280_changeSize(recid);if(menuContainer)menuContainer.style.transition='none'}});Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t280_changeSize(recid)})});if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){document.body.classList.remove('t280_opened');menu.classList.remove('t280__main_opened')})}
var submenuLinks=rec.querySelectorAll('.t-menusub__link-item');Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){document.body.classList.remove('t280_opened');if(menu)menu.classList.remove('t280__main_opened')})})}
function t280_changeSize(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t280__menu');var menuBottom=rec.querySelector('.t280__bottom');var menuContainer=rec.querySelector('.t280__container');var menuWrapper=rec.querySelector('.t280__menu__wrapper');setTimeout(function(){var menuHeight=menu?menu.offsetHeight:0;var menuBottomHeight=menuBottom?menuBottom.offsetHeight:0;var menuContainerHeight=menuContainer?menuContainer.offsetHeight:0;var padding=140;if(menuHeight>document.documentElement.clientHeight-(menuBottomHeight+menuContainerHeight+padding)){if(menuWrapper)menuWrapper.classList.add('t280__menu_static')}else{if(menuWrapper)menuWrapper.classList.remove('t280__menu_static')}},100)}
function t280_changeBgOpacityMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlocks=rec.querySelectorAll('.t280__container__bg');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity2');var menuShadow=menu.getAttribute('data-menu-shadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t280_appearMenu(){var menuBlocks=document.querySelectorAll('.t280');Array.prototype.forEach.call(menuBlocks,function(menuBlock){var menu=menuBlock.querySelector('.t280__positionfixed');if(menu){var appearOffset=menuBlock.getAttribute('data-appearoffset');if(appearOffset&&appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(isNaN(appearOffset))return;if(window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t280_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t280_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t280_slideUpElement(menu,menuHeight,direction){var diff=direction==='toTop'?0:menuHeight;var diffOpacity=direction==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=direction==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=direction==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(direction==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(direction==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t280_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t280__menu a[href=\''+url+'\'], '+'.t280__menu a[href=\''+url+'/\'], '+'.t280__menu a[href=\''+pathname+'\'], '+'.t280__menu a[href=\'/'+pathname+'\'], '+'.t280__menu a[href=\''+pathname+'/\'], '+'.t280__menu a[href=\'/'+pathname+'/\']'+(hash?', .t280__menu a[href=\''+hash+'\']':'')+(hash?', .t280__menu a[href=\'/'+hash+'\']':'')+(hash?', .t280__menu a[href=\''+hash+'/\']':'')+(hash?', .t280__menu a[href=\'/'+hash+'/\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t280__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t734_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var coverBlock=document.querySelector('.t830');if(coverBlock){var slidesWrapper=rec.querySelector('.t-slds__items-wrapper');if(slidesWrapper&&slidesWrapper.classList.contains('t-slds_animated-none')){t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})}else{setTimeout(function(){t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})},500)}}else{t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})}
var currentCoverBlock=rec.querySelector('.t734');if(currentCoverBlock){if(typeof jQuery!=='undefined'){$(currentCoverBlock).on('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}else{currentCoverBlock.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}}}
function t754__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t754__hoverZoom_init(recid);t754_initPopup(recid);t754__updateLazyLoad(recid);t754__alignButtons_init(recid);t_onFuncLoad('t_store_addProductQuantityEvents',function(){t754_initProductQuantity(recid)});if(typeof jQuery!=='undefined'){$('body').trigger('twishlist_addbtn')}else{var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);document.body.dispatchEvent(event)}},500)}
function t754_initProductQuantity(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var productList=rec.querySelectorAll('.t754__col, .t754__product-full');Array.prototype.forEach.call(productList,function(product){if(typeof jQuery!=='undefined'){t_store_addProductQuantityEvents($(product))}else{t_store_addProductQuantityEvents(product)}})}
function t754__showMore(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var wrapperBlock=rec.querySelector('.t754');if(!wrapperBlock)return;var productColumns=wrapperBlock.querySelectorAll('.t754__col');var cardsSize=productColumns.length;var cardsCount=parseInt(wrapperBlock.getAttribute('data-show-count'),10);if(isNaN(cardsCount)||cardsCount<1)return;Array.prototype.forEach.call(productColumns,function(column){column.style.display='none'});for(var i=0;i<cardsCount;i++){if(productColumns[i]){productColumns[i].style.display='inline-block'}}
var showMoreButton=wrapperBlock.querySelector('.t754__showmore');if(!showMoreButton)return;if(showMoreButton.querySelector('td').textContent===''){showMoreButton.querySelector('td').textContent=t754__dict()}
if(cardsCount<productColumns.length){showMoreButton.style.display='inline-block'}
t754__showSeparator(wrapperBlock,cardsCount);showMoreButton.addEventListener('click',function(){var currentColumns=wrapperBlock.querySelectorAll('.t754__col');var currentColumnsShowed=0;Array.prototype.forEach.call(currentColumns,function(column){if(column.style.display==='inline-block'){++currentColumnsShowed}});for(var i=0;i<cardsCount+currentColumnsShowed;i++){if(currentColumns[i]){currentColumns[i].style.display='inline-block'}}
if(cardsCount+currentColumnsShowed>=cardsSize){showMoreButton.style.display='none'}
if(!document.querySelector('.t-records').getAttribute('data-tilda-mode')){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
t754__showSeparator(wrapperBlock,cardsCount+currentColumnsShowed);if(wrapperBlock.querySelector('[data-buttons-v-align]')){t754__alignButtons(recid)}})}
function t754__showSeparator(rec,cardsCount){if(rec instanceof jQuery){rec=rec.get(0)}
var allSeparators=rec.querySelectorAll('.t754__separator_number');Array.prototype.forEach.call(allSeparators,function(separator){separator.classList.add('t754__separator_hide');if(separator.getAttribute('data-product-separator-number')<=cardsCount){separator.classList.remove('t754__separator_hide')}})}
function t754__dict(){var dictionary={EN:'Load more',RU:'Загрузить ещё',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var language=window.browserLang;return dictionary[language]?dictionary[language]:dictionary.EN}
function t754__alignButtons_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;if(!rec.querySelector('[data-buttons-v-align]')){return}
try{t754__alignButtons(recid);if(document.querySelector('.t-records').getAttribute('data-tilda-mode')==='edit'){setInterval(function(){t754__alignButtons(recid)},200)}
window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.isMobile){return}
t754__alignButtons(recid)},200));if(typeof jQuery!=='undefined'){$('#rec'+recid).find('.t754').bind('displayChanged',function(){t754__alignButtons(recid)})}else{var wrapperBlock=rec.querySelector('.t754');if(wrapperBlock){wrapperBlock.addEventListener('displayChanged',function(){t754__alignButtons(recid)})}}
if(window.isMobile){window.addEventListener('orientationchange',function(){t754__alignButtons(recid)})}}catch(error){console.log('buttons-v-align error: '+error.message)}}
function t754__alignButtons(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var wrappers=rec.querySelectorAll('.t754__textwrapper');var maxHeight=0;var container=rec.querySelector('.t754__parent');if(!container)return;var itemsInRow=parseInt(container.getAttribute('data-blocks-per-row'),10);if(!itemsInRow){itemsInRow=3}
var mobileView=window.innerWidth<=480;var tableView=window.innerWidth<=960&&window.innerWidth>480;var mobileOneRow=window.innerWidth<=960&&rec.querySelector('.t754__container_mobile-flex');var mobileTwoItemsInRow=window.innerWidth<=480&&rec.querySelector('.t754 .mobile-two-columns');if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var count=1;var wrappersInRow=[];Array.prototype.forEach.call(wrappers,function(element){element.style.height='auto';if(itemsInRow===1){element.style.height='auto'}else{wrappersInRow.push(element);if(element.offsetHeight>maxHeight){maxHeight=element.offsetHeight}
Array.prototype.forEach.call(wrappersInRow,function(wrapper){wrapper.style.height=maxHeight+'px'});if(count===itemsInRow){count=0;maxHeight=0;wrappersInRow=[]}
count++}})}
function t754__hoverZoom_init(recid){if(window.isMobile)return;var rec=document.getElementById('rec'+recid);if(!rec)return;try{if(!rec.querySelector('[data-hover-zoom]')){return}
var hoverScript='https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js';if(document.querySelector("script[src^='"+hoverScript+"']")){t_onFuncLoad('t_hoverZoom_init',function(){t_hoverZoom_init(recid)})}else{var script=document.createElement('script');script.type='text/javascript';script.src=hoverScript;script.onload=function(){setTimeout(function(){t_hoverZoom_init(recid)},500)};script.onerror=function(error){console.log('Upload script error: ',error)};document.head.appendChild(script)}}catch(error){console.log('Zoom image init error: '+error.message)}}
function t754__updateLazyLoad(recid){var scrollContainer=document.querySelector('#rec'+recid+' .t754__container_mobile-flex');var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t754_initPopup(recid){var rec=document.getElementById('rec'+recid);var popup=rec.querySelector('.t-popup');if(!rec)return;var body=document.body;var popup=rec.querySelector('.t-popup');var linksProd=rec.querySelectorAll('[href^="#prodpopup"]');Array.prototype.forEach.call(linksProd,function(link){link.addEventListener('click',clickOnceHandler,!1);function clickOnceHandler(event){event.preventDefault();var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t754__product-'+productLid)});link.removeEventListener('click',clickOnceHandler,!1)}
link.addEventListener('click',function(event){event.preventDefault();var isT1002Button=event.target.classList.contains('t1002__addBtn')||event.target.parentNode.classList.contains('t1002__addBtn');if(isT1002Button)return;t754_showPopup(recid);var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');var productFull=popup.querySelector('.js-product[data-product-lid="'+productLid+'"]');productFull.style.display='block';var analitics=link.getAttribute('data-track-popup');if(analitics){var productName=productFull.querySelector('.js-product-name');if(productName){var virtTitle=productName.textContent;if(!virtTitle){virtTitle='prod'+productLid}
Tilda.sendEventToStatistics(analitics,virtTitle)}}
var currentUrl=window.location.href;if(currentUrl.indexOf('#!/tproduct/')<0&&currentUrl.indexOf('%23!/tproduct/')<0&&currentUrl.indexOf('#%21%2Ftproduct%2F')<0){if(history.replaceState){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+productLid)}}
t754_updateSlider(recid+' #t754__product-'+productLid);if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})});if(popup){popup.addEventListener('mousedown',function(event){var windowWidth=window.innerWidth;var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(event.clientX>windowWithoutScrollBar){return}
if(event.target===this){t754_closePopup(body,popup)}})}
var closeButtons=rec.querySelectorAll('.t-popup__close, .t754__close-text');Array.prototype.forEach.call(closeButtons,function(button){button.addEventListener('click',function(){t754_closePopup(body,popup)})});document.addEventListener('keydown',function(event){var isGalleryShowedOldLib=document.body.classList.contains('t-zoomer__show');if(isGalleryShowedOldLib)return;var isGalleryShowedNewLib=document.body.classList.contains('t-zoomer__active');if(isGalleryShowedNewLib)return;var isPopupShowed=document.body.classList.contains('t-body_popupshowed');if(!isPopupShowed)return;if(popup&&popup.classList.contains('t-popup_show')){if(event.keyCode===27){t754_closePopup(body,popup)}}});if(!document.getElementById('record'+recid)){t754_checkUrl(recid)}
t754_copyTypography(recid)}
function t754_showPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var popup=rec.querySelector('.t-popup');var fullProducts=popup.querySelectorAll('.t754__product-full');Array.prototype.forEach.call(fullProducts,function(product){product.style.display='none'});popup.style.display='block';setTimeout(function(){popup.querySelector('.t-popup__container').classList.add('t-popup__container-animated');popup.classList.add('t-popup_show');if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},50);var body=document.body;body.classList.add('t-body_popupshowed');if(typeof jQuery!=='undefined'){$('body').trigger('twishlist_addbtn')}else{var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event)}}
function t754_closePopup(body,popup){var fullProducts=popup.querySelectorAll('.t754__product-full');body.classList.remove('t-body_popupshowed');popup.classList.remove('t-popup_show');var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tproduct/');if(typeof jQuery!=='undefined'){$('body').trigger('twishlist_addbtn')}else{var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event)}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=currentUrl.indexOf('%23!/tproduct/');if(indexToRemove<0){indexToRemove=currentUrl.indexOf('#%21%2Ftproduct%2F')}}
currentUrl=currentUrl.substring(0,indexToRemove);setTimeout(function(){popup.scrollTop=0;popup.style.display='none';Array.prototype.forEach.call(fullProducts,function(product){product.style.display='none'});if(history.replaceState){window.history.replaceState('','',currentUrl)}},300)}
function t754_updateSlider(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var slider=rec.querySelector('.t-slds__container');var paddingLeft=parseInt(slider.style.paddingLeft)||0;var paddingRight=parseInt(slider.style.paddingRight)||0;var sliderWrapper=rec.querySelector('.t-slds__items-wrapper');var sliderWidth=slider.clientWidth-(paddingLeft+paddingRight);var pos=parseFloat(sliderWrapper.getAttribute('data-slider-pos'));sliderWrapper.style.transform='translate3d(-'+sliderWidth*pos+'px, 0, 0)';t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t754_checkUrl(recid){var currentUrl=window.location.href;var tprodIndex=currentUrl.indexOf('#!/tproduct/');if(tprodIndex===-1){tprodIndex=currentUrl.indexOf('%23!/tproduct/');if(tprodIndex===-1){tprodIndex=currentUrl.indexOf('#%21%2Ftproduct%2F')}}
if(tprodIndex!==-1){var currentUrl=currentUrl.substring(tprodIndex,currentUrl.length);var curProdLid=currentUrl.substring(currentUrl.indexOf('-')+1,currentUrl.length);if(currentUrl.indexOf(recid)===-1)return;var rec=document.getElementById('rec'+recid);if(!rec)return;if(currentUrl.indexOf(recid)!==0&&rec.querySelector('[data-product-lid="'+curProdLid+'"]')){var currentLink=rec.querySelector('[data-product-lid="'+curProdLid+'"] [href^="#prodpopup"]');var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);if(currentLink){currentLink.dispatchEvent(event)}}}}
function t754_removeSizeStyles(styleStr){if(styleStr&&(styleStr.indexOf('font-size')!==-1||styleStr.indexOf('padding-top')!==-1||styleStr.indexOf('padding-bottom')!==-1)){var styleStrSplitted=styleStr.split(';');styleStr='';for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')!==-1||styleStrSplitted[i].indexOf('padding-top')!==-1||styleStrSplitted[i].indexOf('padding-bottom')!==-1){styleStrSplitted.splice(i,1);i--;continue}
if(!styleStrSplitted[i]){continue}
styleStr+=styleStrSplitted[i]+';'}}
return styleStr}
function t754_copyTypography(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var productTitle=rec.querySelector('.t754__title');var productDescription=rec.querySelector('.t754__descr');if(!productTitle||!productDescription){return}
var titleStyle=productTitle.getAttribute('style');var descrStyle=productDescription.getAttribute('style');var popupTitles=rec.querySelectorAll('.t-popup .t754__title');Array.prototype.forEach.call(popupTitles,function(title){title.setAttribute('style',t754_removeSizeStyles(titleStyle))});var popupDescription=rec.querySelectorAll('.t-popup .t754__descr, .t-popup .t754__text');Array.prototype.forEach.call(popupDescription,function(description){description.setAttribute('style',t754_removeSizeStyles(descrStyle))})}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}
function t985_init(recid,searchVariants){var rec=document.querySelector('#rec'+recid);if(!rec)return;if(searchVariants.length>0){t985_addSearchVariants(recid,searchVariants)}
var searchWidgetIcon=rec.querySelectorAll('.t985__search-widget-icon');Array.prototype.forEach.call(searchWidgetIcon,function(widgetIcon){widgetIcon.addEventListener('click',function(){t985_showSearch(rec)})});var closeIcon=rec.querySelector('.t985__close-icon');if(closeIcon){closeIcon.addEventListener('click',function(){t985_hideSearch(rec)})}
var overlay=rec.querySelector('.t985__overlay');if(overlay){overlay.addEventListener('click',function(event){var target=event.target;var parentTarget=target.parentElement;if(!target.classList.contains('.t985__widgetheader')&&!parentTarget.classList.contains('.t985__widgetheader')){t985_hideSearch(rec)}})}}
function t985_addSearchVariants(recid,searchVariants){var rec=document.querySelector('#rec'+recid);if(!rec)return;var container=rec.querySelector('.t985__searchvariants');var searchArray=searchVariants.split(',');Array.prototype.forEach.call(searchArray,function(variant){container.innerHTML+='<div class="t985__searchvariant t-text t-text_xs">'+variant+'</div>'})}
function t985_showSearch(rec){rec.querySelector('.t985__overlay').style.display='block';rec.querySelector('.t985__search-widget-icon').style.display='none'}
function t985_hideSearch(rec){rec.querySelector('.t985__overlay').style.display='none';rec.querySelector('.t985__search-widget-icon').style.display='block'}
function t890_init(recId,offset){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t890');if(!container)return;var button=rec.querySelector('.t890__arrow');var windowOffset='';if(offset){windowOffset=offset}else{windowOffset=window.innerHeight}
rec.setAttribute('data-animationappear','off');rec.style.opacity=1;window.addEventListener('scroll',t_throttle(function(){if(window.pageYOffset>windowOffset){container.style.display='block'}else{t890__fadeOut(container)}},200));button.addEventListener('click',function(){var isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);if(isSafari){t890__animateScrollPolyfill(0)}else{t890__scrollToTop()}})}
function t890__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},20)}
function t890__scrollToTop(){if(window.isIE){window.scrollTo(0,0)}else{window.scrollTo({left:0,top:0,behavior:'smooth'})}}
function t890__animateScrollPolyfill(target){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(target>bottomViewportPoint)target=bottomViewportPoint;if(target===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(target-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if((target-currentPosition<0&&window.pageYOffset<=target)||(target-currentPosition>0&&window.pageYOffset>=target)){clearInterval(timerID);document.body.removeAttribute('data-scrollable')}},10)}